version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" 
    directory: "ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "backend"
    schedule:
      interval: "daily"