version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" 
    directory: "ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker" 
    directory: "ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "server"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "server"
    schedule:
      interval: "daily"